name: PR Build
on: pull_request
jobs:
  code-quality:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: |
          npm ci
          npm run bootstrap
          cd packages/express-openapi
          npm run test


